---
apiVersion: v1
kind: Secret
metadata:
  name: ainekeenan-ainekeenan-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rosa916-rvhvd/ainekeenan-frontend-gitops
